#!/bin/bash
N=$(nproc)

if [[ $# -eq 1 ]]; then
  for ((i = 0 ; i < N ; i++ )); do 
    echo $1 > /sys/bus/cpu/devices/cpu$i/cpufreq/energy_performance_preference
  done

else
  for ((i = 0 ; i < N ; i++ )); do 
    cat /sys/bus/cpu/devices/cpu$i/cpufreq/energy_performance_preference
  done
fi
