#!/bin/bash
N=$(nproc)

if [[ $# -eq 1 ]]; then
  for ((i = 0 ; i < N ; i++ )); do 
    echo $1 > /sys/bus/cpu/devices/cpu$i/cpufreq/energy_performance_preference
  done
fi
cat /sys/bus/cpu/devices/cpu0/cpufreq/energy_performance_available_preferences
for ((i=0; i<N; i++)); do
    printf "cpu%d:%s " "$i" "$(</sys/bus/cpu/devices/cpu$i/cpufreq/energy_performance_preference)"
done
echo

